server:
  port: 7778
spring:
  thymeleaf:
    cache: false

  #配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: db_user
    password: kybb123456
    url: jdbc:mysql://dev-mysql.zhilun-base.com:3306/test_tsc_b?useUnicode=true&characterEncoding=UTF8&useSSL=false
    #邮箱配置
  mail:
    host: smtp.qq.com
    port: 587
    username: 2465668576@qq.com
    password: mgjlurmdqgfieaig
    from: 2465668576@qq.com
    properties:
      mail:
        debug: true
      stmp:
        auth: true
        ssl:
          enable: true

#配置sql映射
mybatis:
  type-aliases-package: com.chapter6
  mapper-locations:
    - mybatis/mapper/*
#配置sql的打印
logging:
  level:
    com.example.demo.dao: debug


